/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export enum Domain_AccountType {
    Bank = "bank",
    Cash = "cash",
    CreditCard = "credit_card",
    Investment = "investment",
    Other = "other"
}

export enum Domain_TransactionType {
    Credit = "credit",
    Debit = "debit",
    Transfer = "transfer",
    Payment = "payment"
}

export interface Dto_AccountResponse {
    color?: string;
    created_at?: string;
    currency?: string;
    icon?: string;
    id?: string;
    initial_balance?: number;
    name?: string;
    tenant_id?: string;
    type?: Domain_AccountType;
    updated_at?: string;
}

export interface Dto_AuthResponse {
    access_token?: string;
    refresh_token?: string;
    user?: Dto_User;
}

export interface Dto_CategoryResponse {
    color?: string;
    created_at?: string;
    created_by?: string;
    icon?: string;
    id?: string;
    name?: string;
    parent_category_id?: string;
    tenant_id?: string;
    updated_at?: string;
    updated_by?: string;
}

export interface Dto_CreateAccountRequest {
    color?: string;
    currency?: string;
    icon?: string;
    initial_balance?: number;
    name: string;
    type: Domain_AccountType;
}

export interface Dto_CreateCategoryRequest {
    color?: string;
    icon?: string;
    name: string;
    parent_category_id?: string;
}

export interface Dto_CreateTagRequest {
    name: string;
}

export interface Dto_CreateTenantRequest {
    name: string;
}

export interface Dto_CreateTransactionRequest {
    /** YYYYMM */
    accrual_month: string;
    amount: number;
    category_id: string;
    comments?: string;
    due_date: string;
    from_account_id: string;
    installments?: number;
    is_recurring?: boolean;
    payment_date?: string;
    tag_ids?: Array<string>;
    to_account_id?: string;
    transaction_type: 'credit' | 'debit' | 'transfer' | 'payment';
}

export interface Dto_RefreshTokenRequest {
    refresh_token: string;
}

export interface Dto_RegisterRequest {
    email: string;
    full_name: string;
    password: string;
}

export interface Dto_TagResponse {
    created_at?: string;
    created_by?: string;
    deactivated_at?: string;
    id?: string;
    name?: string;
    tenant_id?: string;
    updated_at?: string;
    updated_by?: string;
}

export interface Dto_TenantResponse {
    created_at?: string;
    id?: string;
    name?: string;
    updated_at?: string;
}

export interface Dto_TransactionResponse {
    accrual_month?: string;
    amount?: number;
    category_id?: string;
    comments?: string;
    created_at?: string;
    created_by?: string;
    currency?: string;
    deactivated_at?: string;
    deactivated_by?: string;
    due_date?: string;
    from_account_id?: string;
    id?: string;
    parent_transaction_id?: string;
    payment_date?: string;
    tenant_id?: string;
    to_account_id?: string;
    transaction_type?: Domain_TransactionType;
    updated_at?: string;
    updated_by?: string;
}

export interface Dto_UpdateAccountRequest {
    color?: string;
    icon?: string;
    initial_balance?: number;
    name: string;
}

export interface Dto_UpdateCategoryRequest {
    color?: string;
    icon?: string;
    name: string;
    parent_category_id?: string;
}

export interface Dto_UpdateTagRequest {
    name: string;
}

export interface Dto_UpdateUserRequest {
    email: string;
    name: string;
}

export interface Dto_User {
    email?: string;
    id?: string;
}

export interface Dto_UserResponse {
    created_at?: string;
    email?: string;
    id?: string;
    name?: string;
    updated_at?: string;
}

export interface Dto_UserTenantResponse {
    name?: string;
    tenant_id?: string;
}

export interface Handler_ErrorResponse {
    error?: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
