/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Accounts controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_FINTRACK, CLIENT_CONTEXT_TOKEN_FINTRACK } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, Dto_AccountResponse, Dto_CreateAccountRequest } from "../models";

@Injectable({ providedIn: "root" })
export class AccountsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_FINTRACK);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_FINTRACK;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'Fintrack');
    }

    accountsGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<Dto_AccountResponse>>;
    accountsGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<Dto_AccountResponse>>>;
    accountsGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<Dto_AccountResponse>>>;
    /** list accounts by tenant ID */
    accountsGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/accounts`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    accountsPost(dtoCreateAccountRequest: Dto_CreateAccountRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_AccountResponse>;
    accountsPost(dtoCreateAccountRequest: Dto_CreateAccountRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_AccountResponse>>;
    accountsPost(dtoCreateAccountRequest: Dto_CreateAccountRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_AccountResponse>>;
    /** create a new account */
    accountsPost(dtoCreateAccountRequest: Dto_CreateAccountRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/accounts`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, dtoCreateAccountRequest, requestOptions);
    }

    accountsIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_AccountResponse>;
    accountsIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_AccountResponse>>;
    accountsIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_AccountResponse>>;
    /** get account by ID */
    accountsIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/accounts/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
