/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Auth controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_FINTRACK, CLIENT_CONTEXT_TOKEN_FINTRACK } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, Dto_AuthResponse, Dto_RefreshTokenRequest, Dto_RegisterRequest } from "../models";

@Injectable({ providedIn: "root" })
export class AuthService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_FINTRACK);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_FINTRACK;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'Fintrack');
    }

    authLoginPost(username: string, password: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_AuthResponse>;
    authLoginPost(username: string, password: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_AuthResponse>>;
    authLoginPost(username: string, password: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_AuthResponse>>;
    /** Login with username and password */
    authLoginPost(username: string, password: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/auth/login`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (username !== undefined) {
            formData.append('username', String(username));
        }
        if (password !== undefined) {
            formData.append('password', String(password));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    authRefreshTokenPost(dtoRefreshTokenRequest: Dto_RefreshTokenRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_AuthResponse>;
    authRefreshTokenPost(dtoRefreshTokenRequest: Dto_RefreshTokenRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_AuthResponse>>;
    authRefreshTokenPost(dtoRefreshTokenRequest: Dto_RefreshTokenRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_AuthResponse>>;
    /** Refresh access token using refresh token */
    authRefreshTokenPost(dtoRefreshTokenRequest: Dto_RefreshTokenRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/auth/refresh-token`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, dtoRefreshTokenRequest, requestOptions);
    }

    authRegisterPost(dtoRegisterRequest: Dto_RegisterRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_AuthResponse>;
    authRegisterPost(dtoRegisterRequest: Dto_RegisterRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_AuthResponse>>;
    authRegisterPost(dtoRegisterRequest: Dto_RegisterRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_AuthResponse>>;
    /** Register a new user with full name, email and password */
    authRegisterPost(dtoRegisterRequest: Dto_RegisterRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/auth/register`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, dtoRegisterRequest, requestOptions);
    }
}
