/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Categories controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_FINTRACK, CLIENT_CONTEXT_TOKEN_FINTRACK } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, Dto_CategoryResponse, Dto_CreateCategoryRequest, Dto_UpdateCategoryRequest } from "../models";

@Injectable({ providedIn: "root" })
export class CategoriesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_FINTRACK);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_FINTRACK;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'Fintrack');
    }

    categoriesGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<Dto_CategoryResponse>>;
    categoriesGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<Dto_CategoryResponse>>>;
    categoriesGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<Dto_CategoryResponse>>>;
    /** Get all categories for the authenticated user's tenant */
    categoriesGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categories`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    categoriesPost(dtoCreateCategoryRequest: Dto_CreateCategoryRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_CategoryResponse>;
    categoriesPost(dtoCreateCategoryRequest: Dto_CreateCategoryRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_CategoryResponse>>;
    categoriesPost(dtoCreateCategoryRequest: Dto_CreateCategoryRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_CategoryResponse>>;
    /** Create a new category for the authenticated user's tenant */
    categoriesPost(dtoCreateCategoryRequest: Dto_CreateCategoryRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categories`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, dtoCreateCategoryRequest, requestOptions);
    }

    categoriesIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_CategoryResponse>;
    categoriesIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_CategoryResponse>>;
    categoriesIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_CategoryResponse>>;
    /** Get a category by its ID */
    categoriesIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categories/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    categoriesIdPut(id: string, dtoUpdateCategoryRequest: Dto_UpdateCategoryRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_CategoryResponse>;
    categoriesIdPut(id: string, dtoUpdateCategoryRequest: Dto_UpdateCategoryRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_CategoryResponse>>;
    categoriesIdPut(id: string, dtoUpdateCategoryRequest: Dto_UpdateCategoryRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_CategoryResponse>>;
    /** Update an existing category */
    categoriesIdPut(id: string, dtoUpdateCategoryRequest: Dto_UpdateCategoryRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categories/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, dtoUpdateCategoryRequest, requestOptions);
    }

    categoriesIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    categoriesIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    categoriesIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Soft Delete a category */
    categoriesIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categories/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
