/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Tags controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_FINTRACK, CLIENT_CONTEXT_TOKEN_FINTRACK } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, Dto_TagResponse, Dto_CreateTagRequest, Dto_UpdateTagRequest } from "../models";

@Injectable({ providedIn: "root" })
export class TagsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_FINTRACK);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_FINTRACK;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'Fintrack');
    }

    tagsGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<Dto_TagResponse>>;
    tagsGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<Dto_TagResponse>>>;
    tagsGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<Dto_TagResponse>>>;
    /** Get all tags for the authenticated user's tenant */
    tagsGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/tags`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    tagsPost(dtoCreateTagRequest: Dto_CreateTagRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_TagResponse>;
    tagsPost(dtoCreateTagRequest: Dto_CreateTagRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_TagResponse>>;
    tagsPost(dtoCreateTagRequest: Dto_CreateTagRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_TagResponse>>;
    /** Create a new tag for the authenticated user's tenant */
    tagsPost(dtoCreateTagRequest: Dto_CreateTagRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/tags`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, dtoCreateTagRequest, requestOptions);
    }

    tagsIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_TagResponse>;
    tagsIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_TagResponse>>;
    tagsIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_TagResponse>>;
    /** Get a tag by its ID */
    tagsIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/tags/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    tagsIdPut(id: string, dtoUpdateTagRequest: Dto_UpdateTagRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_TagResponse>;
    tagsIdPut(id: string, dtoUpdateTagRequest: Dto_UpdateTagRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_TagResponse>>;
    tagsIdPut(id: string, dtoUpdateTagRequest: Dto_UpdateTagRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_TagResponse>>;
    /** Update an existing tag */
    tagsIdPut(id: string, dtoUpdateTagRequest: Dto_UpdateTagRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/tags/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, dtoUpdateTagRequest, requestOptions);
    }

    tagsIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    tagsIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    tagsIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Soft Delete a tag */
    tagsIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/tags/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
