/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Tenants controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_FINTRACK, CLIENT_CONTEXT_TOKEN_FINTRACK } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { Dto_CreateTenantRequest, RequestOptions, Dto_TenantResponse } from "../models";

@Injectable({ providedIn: "root" })
export class TenantsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_FINTRACK);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_FINTRACK;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'Fintrack');
    }

    tenantsPost(dtoCreateTenantRequest: Dto_CreateTenantRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_TenantResponse>;
    tenantsPost(dtoCreateTenantRequest: Dto_CreateTenantRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_TenantResponse>>;
    tenantsPost(dtoCreateTenantRequest: Dto_CreateTenantRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_TenantResponse>>;
    /** Create a new tenant (workspace) and links the creator to it. */
    tenantsPost(dtoCreateTenantRequest: Dto_CreateTenantRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/tenants`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, dtoCreateTenantRequest, requestOptions);
    }
}
