/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Transactions controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_FINTRACK, CLIENT_CONTEXT_TOKEN_FINTRACK } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, Dto_TransactionResponse } from "../models";

@Injectable({ providedIn: "root" })
export class TransactionsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_FINTRACK);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_FINTRACK;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'Fintrack');
    }

    transactionsGet(accrualMonth?: string, accountId?: string, transactionType?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<Dto_TransactionResponse>>;
    transactionsGet(accrualMonth?: string, accountId?: string, transactionType?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<Dto_TransactionResponse>>>;
    transactionsGet(accrualMonth?: string, accountId?: string, transactionType?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<Dto_TransactionResponse>>>;
    /** Lists transactions for the tenant, optionally filtered. */
    transactionsGet(accrualMonth?: string, accountId?: string, transactionType?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/transactions`;

        let params = new HttpParams();
        if (accrualMonth != null) {
            params = HttpParamsBuilder.addToHttpParams(params, accrualMonth, 'accrual_month');
        }
        if (accountId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, accountId, 'account_id');
        }
        if (transactionType != null) {
            params = HttpParamsBuilder.addToHttpParams(params, transactionType, 'transaction_type');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    transactionsPost(observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_TransactionResponse>;
    transactionsPost(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_TransactionResponse>>;
    transactionsPost(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_TransactionResponse>>;
    /** Creates a new transaction for the authenticated user's tenant. */
    transactionsPost(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/transactions`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, null, requestOptions);
    }

    transactionsIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_TransactionResponse>;
    transactionsIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_TransactionResponse>>;
    transactionsIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_TransactionResponse>>;
    /** Retrieves a transaction by its ID. */
    transactionsIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/transactions/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    transactionsIdPut(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_TransactionResponse>;
    transactionsIdPut(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_TransactionResponse>>;
    transactionsIdPut(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_TransactionResponse>>;
    /** Updates a transaction by ID. */
    transactionsIdPut(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/transactions/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, null, requestOptions);
    }

    transactionsIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    transactionsIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    transactionsIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Soft-deletes a transaction by ID. */
    transactionsIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/transactions/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
