/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Users controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_FINTRACK, CLIENT_CONTEXT_TOKEN_FINTRACK } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, Dto_UserResponse, Dto_UpdateUserRequest, Dto_UserTenantResponse } from "../models";

@Injectable({ providedIn: "root" })
export class UsersService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_FINTRACK);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_FINTRACK;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'Fintrack');
    }

    usersProfileGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_UserResponse>;
    usersProfileGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_UserResponse>>;
    usersProfileGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_UserResponse>>;
    /** Get the profile of the authenticated user */
    usersProfileGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/users/profile`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    usersProfilePut(dtoUpdateUserRequest: Dto_UpdateUserRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<Dto_UserResponse>;
    usersProfilePut(dtoUpdateUserRequest: Dto_UpdateUserRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Dto_UserResponse>>;
    usersProfilePut(dtoUpdateUserRequest: Dto_UpdateUserRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Dto_UserResponse>>;
    /** Update the profile of the authenticated user */
    usersProfilePut(dtoUpdateUserRequest: Dto_UpdateUserRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/users/profile`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, dtoUpdateUserRequest, requestOptions);
    }

    usersTenantsGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<Dto_UserTenantResponse>>;
    usersTenantsGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<Dto_UserTenantResponse>>>;
    usersTenantsGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<Dto_UserTenantResponse>>>;
    /** Get the tenants of the authenticated user */
    usersTenantsGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/users/tenants`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
