/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* `httpResource` is still an experimental feature - NOT PRODUCTION READY
* Generated Angular service for AccountsResource
* Do not edit this file manually
*/
import { HttpContext, HttpContextToken, HttpHeaders, HttpParams, httpResource, HttpResourceOptions, HttpResourceRef, HttpResourceRequest } from "@angular/common/http";
import { inject, Injectable, Signal } from "@angular/core";
import { BASE_PATH_FINTRACK, CLIENT_CONTEXT_TOKEN_FINTRACK } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { Dto_AccountResponse } from "../models";

@Injectable({ providedIn: "root" })
export class AccountsResource {
    private readonly basePath: string = inject(BASE_PATH_FINTRACK);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_FINTRACK;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'Fintrack');
    }

    accountsGet(resourceOptions: HttpResourceOptions<Array<Dto_AccountResponse>, unknown> & { defaultValue: NoInfer<Array<Dto_AccountResponse>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_AccountResponse>>;
    accountsGet(resourceOptions?: HttpResourceOptions<Array<Dto_AccountResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_AccountResponse> | undefined>;
    /** list accounts by tenant ID */
    accountsGet(resourceOptions?: HttpResourceOptions<Array<Dto_AccountResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_AccountResponse> | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/accounts`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    accountsIdGet(id: Signal<string> | string, resourceOptions: HttpResourceOptions<Dto_AccountResponse, unknown> & { defaultValue: NoInfer<Dto_AccountResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_AccountResponse>;
    accountsIdGet(id: Signal<string> | string, resourceOptions?: HttpResourceOptions<Dto_AccountResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_AccountResponse | undefined>;
    /** get account by ID */
    accountsIdGet(id: Signal<string> | string, resourceOptions?: HttpResourceOptions<Dto_AccountResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_AccountResponse | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/accounts/${typeof id === 'function' ? id() : id}`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }
}
