/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* `httpResource` is still an experimental feature - NOT PRODUCTION READY
* Generated Angular service for CategoriesResource
* Do not edit this file manually
*/
import { HttpContext, HttpContextToken, HttpHeaders, HttpParams, httpResource, HttpResourceOptions, HttpResourceRef, HttpResourceRequest } from "@angular/common/http";
import { inject, Injectable, Signal } from "@angular/core";
import { BASE_PATH_FINTRACK, CLIENT_CONTEXT_TOKEN_FINTRACK } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { Dto_CategoryResponse } from "../models";

@Injectable({ providedIn: "root" })
export class CategoriesResource {
    private readonly basePath: string = inject(BASE_PATH_FINTRACK);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_FINTRACK;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'Fintrack');
    }

    categoriesGet(resourceOptions: HttpResourceOptions<Array<Dto_CategoryResponse>, unknown> & { defaultValue: NoInfer<Array<Dto_CategoryResponse>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_CategoryResponse>>;
    categoriesGet(resourceOptions?: HttpResourceOptions<Array<Dto_CategoryResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_CategoryResponse> | undefined>;
    /** Get all categories for the authenticated user's tenant */
    categoriesGet(resourceOptions?: HttpResourceOptions<Array<Dto_CategoryResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_CategoryResponse> | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/categories`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    categoriesIdGet(id: Signal<string> | string, resourceOptions: HttpResourceOptions<Dto_CategoryResponse, unknown> & { defaultValue: NoInfer<Dto_CategoryResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_CategoryResponse>;
    categoriesIdGet(id: Signal<string> | string, resourceOptions?: HttpResourceOptions<Dto_CategoryResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_CategoryResponse | undefined>;
    /** Get a category by its ID */
    categoriesIdGet(id: Signal<string> | string, resourceOptions?: HttpResourceOptions<Dto_CategoryResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_CategoryResponse | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/categories/${typeof id === 'function' ? id() : id}`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }
}
