/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { AccountsResource } from "./accounts.resource";
export { CategoriesResource } from "./categories.resource";
export { TagsResource } from "./tags.resource";
export { TransactionsResource } from "./transactions.resource";
export { UsersResource } from "./users.resource";
