/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* `httpResource` is still an experimental feature - NOT PRODUCTION READY
* Generated Angular service for TagsResource
* Do not edit this file manually
*/
import { HttpContext, HttpContextToken, HttpHeaders, HttpParams, httpResource, HttpResourceOptions, HttpResourceRef, HttpResourceRequest } from "@angular/common/http";
import { inject, Injectable, Signal } from "@angular/core";
import { BASE_PATH_FINTRACK, CLIENT_CONTEXT_TOKEN_FINTRACK } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { Dto_TagResponse } from "../models";

@Injectable({ providedIn: "root" })
export class TagsResource {
    private readonly basePath: string = inject(BASE_PATH_FINTRACK);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_FINTRACK;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'Fintrack');
    }

    tagsGet(resourceOptions: HttpResourceOptions<Array<Dto_TagResponse>, unknown> & { defaultValue: NoInfer<Array<Dto_TagResponse>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_TagResponse>>;
    tagsGet(resourceOptions?: HttpResourceOptions<Array<Dto_TagResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_TagResponse> | undefined>;
    /** Get all tags for the authenticated user's tenant */
    tagsGet(resourceOptions?: HttpResourceOptions<Array<Dto_TagResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_TagResponse> | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/tags`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    tagsIdGet(id: Signal<string> | string, resourceOptions: HttpResourceOptions<Dto_TagResponse, unknown> & { defaultValue: NoInfer<Dto_TagResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_TagResponse>;
    tagsIdGet(id: Signal<string> | string, resourceOptions?: HttpResourceOptions<Dto_TagResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_TagResponse | undefined>;
    /** Get a tag by its ID */
    tagsIdGet(id: Signal<string> | string, resourceOptions?: HttpResourceOptions<Dto_TagResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_TagResponse | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/tags/${typeof id === 'function' ? id() : id}`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }
}
