/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* `httpResource` is still an experimental feature - NOT PRODUCTION READY
* Generated Angular service for TransactionsResource
* Do not edit this file manually
*/
import { HttpContext, HttpContextToken, HttpHeaders, HttpParams, httpResource, HttpResourceOptions, HttpResourceRef, HttpResourceRequest } from "@angular/common/http";
import { inject, Injectable, Signal } from "@angular/core";
import { BASE_PATH_FINTRACK, CLIENT_CONTEXT_TOKEN_FINTRACK } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { Dto_TransactionResponse } from "../models";

@Injectable({ providedIn: "root" })
export class TransactionsResource {
    private readonly basePath: string = inject(BASE_PATH_FINTRACK);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_FINTRACK;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'Fintrack');
    }

    transactionsGet(accrualMonth: Signal<string | undefined> | string | undefined, accountId: Signal<string | undefined> | string | undefined, transactionType: Signal<string | undefined> | string | undefined, resourceOptions: HttpResourceOptions<Array<Dto_TransactionResponse>, unknown> & { defaultValue: NoInfer<Array<Dto_TransactionResponse>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_TransactionResponse>>;
    transactionsGet(accrualMonth?: Signal<string | undefined> | string, accountId?: Signal<string | undefined> | string, transactionType?: Signal<string | undefined> | string, resourceOptions?: HttpResourceOptions<Array<Dto_TransactionResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_TransactionResponse> | undefined>;
    /** Lists transactions for the tenant, optionally filtered. */
    transactionsGet(accrualMonth?: Signal<string | undefined> | string, accountId?: Signal<string | undefined> | string, transactionType?: Signal<string | undefined> | string, resourceOptions?: HttpResourceOptions<Array<Dto_TransactionResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_TransactionResponse> | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const accrualMonthValue = typeof accrualMonth === 'function' ? accrualMonth() : accrualMonth;
            if (accrualMonthValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, accrualMonthValue, 'accrual_month');
            }
            const accountIdValue = typeof accountId === 'function' ? accountId() : accountId;
            if (accountIdValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, accountIdValue, 'account_id');
            }
            const transactionTypeValue = typeof transactionType === 'function' ? transactionType() : transactionType;
            if (transactionTypeValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, transactionTypeValue, 'transaction_type');
            }
            return {
                url: `${this.basePath}/transactions`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    transactionsIdGet(id: Signal<string> | string, resourceOptions: HttpResourceOptions<Dto_TransactionResponse, unknown> & { defaultValue: NoInfer<Dto_TransactionResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_TransactionResponse>;
    transactionsIdGet(id: Signal<string> | string, resourceOptions?: HttpResourceOptions<Dto_TransactionResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_TransactionResponse | undefined>;
    /** Retrieves a transaction by its ID. */
    transactionsIdGet(id: Signal<string> | string, resourceOptions?: HttpResourceOptions<Dto_TransactionResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_TransactionResponse | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/transactions/${typeof id === 'function' ? id() : id}`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }
}
