/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* `httpResource` is still an experimental feature - NOT PRODUCTION READY
* Generated Angular service for UsersResource
* Do not edit this file manually
*/
import { HttpContext, HttpContextToken, HttpHeaders, HttpParams, httpResource, HttpResourceOptions, HttpResourceRef, HttpResourceRequest } from "@angular/common/http";
import { inject, Injectable, Signal } from "@angular/core";
import { BASE_PATH_FINTRACK, CLIENT_CONTEXT_TOKEN_FINTRACK } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { Dto_UserResponse, Dto_UserTenantResponse } from "../models";

@Injectable({ providedIn: "root" })
export class UsersResource {
    private readonly basePath: string = inject(BASE_PATH_FINTRACK);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_FINTRACK;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'Fintrack');
    }

    usersProfileGet(resourceOptions: HttpResourceOptions<Dto_UserResponse, unknown> & { defaultValue: NoInfer<Dto_UserResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_UserResponse>;
    usersProfileGet(resourceOptions?: HttpResourceOptions<Dto_UserResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_UserResponse | undefined>;
    /** Get the profile of the authenticated user */
    usersProfileGet(resourceOptions?: HttpResourceOptions<Dto_UserResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Dto_UserResponse | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/users/profile`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    usersTenantsGet(resourceOptions: HttpResourceOptions<Array<Dto_UserTenantResponse>, unknown> & { defaultValue: NoInfer<Array<Dto_UserTenantResponse>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_UserTenantResponse>>;
    usersTenantsGet(resourceOptions?: HttpResourceOptions<Array<Dto_UserTenantResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_UserTenantResponse> | undefined>;
    /** Get the tenants of the authenticated user */
    usersTenantsGet(resourceOptions?: HttpResourceOptions<Array<Dto_UserTenantResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<Dto_UserTenantResponse> | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/users/tenants`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }
}
